### ISSUE TITLE
Use typeclass pattern to support customization of pprint for various types

### ISSUE THREAD

**Issue by jedesah** [lihaoyi/PPrint#11]
I might have time to work on this at some point...

Just want to make sure there is buy-in before I invest too much time

**Comment by lihaoyi** [comment]
Not going to happen; this was the case before pprint 0.5.0 and it was a disaster

**Comment by ryan-williams** [comment]
sad to hear this / interested in more details if they are available

was excited to use ammonite+pprint in tut, thinking it would allow customizing types' pretty-printed forms

have been developing a `ToLines` type-class with generic auto-derivation ([example](https://github.com/hammerlab/io-utils/blob/io-5.0.0/io/shared/src/test/scala/org/hammerlab/lines/GenericLinesTest.scala#L93-L116)), so far it seems not-terrible, wondering if the ecosystem around scala/shapeless has improved since this was attempted here?
